# Generated by Django 5.2.8 on 2025-12-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_joblisting_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='application_start_date',
            field=models.DateField(blank=True, help_text='Date when applications start opening', null=True),
        ),
    ]
