# Generated by Django 5.2.8 on 2026-01-07 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_add_job_type_and_work_mode'),
        ('recruitment', '0007_joblisting_job_type_joblisting_work_mode'),
    ]

    operations = [
    ]
